# Generated by Django 5.2.9 on 2025-12-04 07:20

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('DRIVER', 'Driver'), ('DISPATCHER', 'Dispatcher'), ('MANAGER', 'Manager')], default='DISPATCHER', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Buggy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField(default=4)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='INACTIVE', max_length=20)),
                ('current_onboard_guests', models.PositiveIntegerField(default=0)),
                ('driver', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_buggy', to=settings.AUTH_USER_MODEL)),
                ('current_poi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.poi')),
            ],
        ),
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_code', models.CharField(max_length=12, unique=True)),
                ('num_guests', models.PositiveIntegerField()),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('guest_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('PICKING_UP', 'Picking up'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('pickup_completed_at', models.DateTimeField(blank=True, null=True)),
                ('dropoff_completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_buggy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='core.buggy')),
                ('dropoff_poi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dropoff_rides', to='core.poi')),
                ('pickup_poi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_rides', to='core.poi')),
            ],
        ),
        migrations.CreateModel(
            name='PoiEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_time_s', models.PositiveIntegerField()),
                ('from_poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_from', to='core.poi')),
                ('to_poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_to', to='core.poi')),
            ],
            options={
                'unique_together': {('from_poi', 'to_poi')},
            },
        ),
        migrations.CreateModel(
            name='BuggyRouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_type', models.CharField(choices=[('PICKUP', 'Pickup'), ('DROPOFF', 'Dropoff')], max_length=10)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ON_ROUTE', 'On route'), ('COMPLETED', 'Completed')], default='PLANNED', max_length=15)),
                ('sequence_index', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('buggy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='core.buggy')),
                ('poi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.poi')),
                ('ride_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='core.riderequest')),
            ],
            options={
                'ordering': ['sequence_index'],
                'unique_together': {('buggy', 'sequence_index')},
            },
        ),
    ]
